### ISSUE TITLE
Tagging a release

### ISSUE THREAD

**Issue by dvershinin** [tokers/zstd-nginx-module#19]
Is possible to tag a release version?

**Comment by tokers** [comment]
@dvershinin Well, I think so; maybe a release number like `0.1.0` would be better?

**Comment by dvershinin** [comment]
@tokers Yes, it would be great.

**Comment by ctrlcctrlv** [comment]
please do this

**Comment by tokers** [comment]
@dvershinin @ctrlcctrlv Just tag a [`0.1.0` release](https://github.com/tokers/zstd-nginx-module/releases/tag/0.1.0).

**Comment by dvershinin** [comment]
Thank you very much.
