### ISSUE TITLE
Invalid module order

### ISSUE THREAD

**Issue by JakubOnderka** [tokers/zstd-nginx-module#30]
Module order is incorrect for compression module. For example, if using `ngx_http_sub_module`, string is not replaced because it it tries to replace content when it is already compressed.

For inspiration you can check  

https://github.com/google/ngx_brotli/blob/a71f9312c2deb28875acc7bacfdd5695a111aa53/filter/config#L70-L85

**Comment by tokers** [comment]
@JakubOnderka Got it, thanks!
